{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:04:21 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(1,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,26);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,19);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(1,8.623395);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,84.26304);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,7.796883);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,55.64951);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,3.734329);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,5.646193);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,9.946316);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,39.29759);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,27.35713);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(1,6.328926);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,16.83982);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,5.542006);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,13.03642);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,3.734329);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,4.008086);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,5.946109);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,11.05598);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,9.215489);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(77);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"203909");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"203912");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"203985");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"203986");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"203987");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"203991");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"203992");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"203994");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"204100");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"204101");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"204113");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"204114");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.947509e-316,2.342633e-310,2.342631e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
