{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:19:26 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(9,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,17.14725);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,6.533304);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,3.675101);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,20.94941);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,3.107015);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,21.50688);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(9,17.90857);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,17.15078);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,16.12073);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,7.706229);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,4.62084);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,3.675101);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,8.585973);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,3.107015);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,8.836456);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(9,8.086679);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,8.688469);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,7.21506);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(35);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205515");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205519");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205526");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205614");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205617");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205618");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205620");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205666");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205667");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"205683");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"205690");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"205694");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.827594e-316,2.350404e-310,8.621509e-316,6.793575e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
