{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 17:32:27 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMPProf","",5,0,5,"");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(1,8);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(2,5);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(4,218);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(5,41);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(1,26.65826);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(2,16.4965);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(4,749.8104);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(5,139.2114);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(1,9.439404);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(2,7.38994);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(4,51.14534);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(5,21.87892);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetEntries(272);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"193834");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"193835");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"193836");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"193998");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"193999");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.671866e-316,9.339849e-316,9.470974e-316,7.868231e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("e");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
