{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 15:38:22 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,39);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,24);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,9.435616);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,9.841687);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,6.267075);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,13.10496);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,3.307564);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,3.099596);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,125.43);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,42.43764);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,84.09559);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,39.11036);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,5.458897);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,5.689355);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,4.446714);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,6.561997);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,3.307564);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,3.099596);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,20.18075);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,11.78331);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,17.80805);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,11.31043);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(102);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"198116");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"198207");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"198208");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"198210");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"198212");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"198213");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"198215");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"198230");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"198249");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"198269");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"198271");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"198272");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.623985e-316,2.355345e-310,5.598542e-316,6.397681e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
