{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 15:38:24 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,39);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,24);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,9.8116);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,9.864654);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,6.789621);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,13.31079);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,3.26512);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,3.176602);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,128.4663);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,42.53921);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,83.89365);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,39.34322);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,5.669903);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,5.701547);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,4.807106);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,6.664867);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,3.26512);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,3.176602);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,20.61095);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,11.81707);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,17.5942);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,11.37102);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(102);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"198116");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"198207");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"198208");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"198210");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"198212");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"198213");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"198215");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"198230");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"198249");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"198269");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"198271");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"198272");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.136002e-316,2.355345e-310,5.624145e-316,6.111151e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
