{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 15:38:26 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,37);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,24);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,6.040076);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,9.687535);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,2.796302);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,12.77352);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(6,3.470296);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,2.766347);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,121.3127);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,45.66022);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,95.87923);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,42.8947);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,4.276443);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,5.610794);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,2.796302);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,6.492639);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(6,3.470296);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,2.766347);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,20.15267);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,12.90961);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,21.6285);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,12.03839);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(99);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"198116");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"198207");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"198208");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"198210");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"198212");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"198213");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"198215");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"198230");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"198249");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"198269");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"198271");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"198272");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.148772e-316,2.355345e-310,5.598529e-316,6.148777e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
