{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 19:00:15 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(1,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,17);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(9,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,17);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(1,7.393972);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,6.902274);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,64.4275);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,20.61698);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(6,3.315524);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,39.17454);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(9,12.75124);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,44.01478);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,12.03642);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,58.83302);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(1,5.228625);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,4.881507);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,15.91239);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,8.455364);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(6,3.315524);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,11.92082);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(9,6.376984);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,12.24048);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,6.95739);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,14.34961);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(76);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205111");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205158");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205193");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205217");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205233");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205236");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205238");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205303");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205310");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"205311");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"205339");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"205344");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(4.86225e-316,2.34065e-310,6.513007e-316,7.173632e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
