{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:09:00 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,14);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(9,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,32.75742);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,6.533304);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,3.675101);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,43.08264);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,2.507836);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,27.17497);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(9,35.78165);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,22.70175);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,2.798433);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,33.36405);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,10.01493);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,4.62084);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,3.675101);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,11.62954);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,2.507836);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,9.284159);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(9,10.53292);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,9.533948);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,2.798433);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,9.727317);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(69);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205515");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205519");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205526");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205614");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205617");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205618");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205620");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205666");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205667");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"205683");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"205690");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"205694");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.231339e-316,2.368481e-310,8.08729e-316,6.146018e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
