{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:08:56 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(9,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,36.85832);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,8.974472);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,3.416081);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,50.7356);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,3.02301);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,39.76915);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(9,37.46761);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,22.24003);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,3.265772);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,49.72862);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,11.12515);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,5.216134);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,3.416081);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,12.69877);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,3.02301);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,11.04143);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(9,10.83142);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,8.438683);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,3.265772);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,12.45918);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(81);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205515");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205519");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205526");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205614");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205617");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205618");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205620");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205666");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205667");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"205683");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"205690");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"205694");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(4.082659e-316,7.291122e-304,2.368479e-310,1.38439e+41,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
