{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:09:02 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,11);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(9,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(10,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,31.33006);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,7.033158);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,4.226984);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,39.65775);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,3.300939);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,29.31812);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(9,34.62134);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(10,25.07424);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,3.241374);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,33.50614);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,10.52766);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,4.973955);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,4.226984);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,12.04458);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,3.300939);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,10.45418);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(9,11.04825);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(10,10.53057);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,3.241374);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,10.62052);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(59);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"205515");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"205519");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"205526");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"205614");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"205617");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"205618");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"205620");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"205666");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"205667");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"205683");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"205690");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"205694");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.083969e-316,8.084014e-316,8.696329e-316,8.905594e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
