{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:08:58 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(9,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,39.18675);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,9.527883);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,3.354441);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,52.10248);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,3.23997);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,41.70508);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(9,39.13013);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,23.06034);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,3.424348);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,52.99207);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,11.8644);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,5.502614);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,3.354441);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,13.03985);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,3.23997);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,11.57464);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(9,11.31259);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,8.743762);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,3.424348);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,13.27288);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(81);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205515");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205519");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205526");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205614");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205617");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205618");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205620");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205666");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205667");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"205683");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"205690");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"205694");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.964612e-316,2.368481e-310,7.964627e-316,7.964613e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
