{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:55:01 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMPProf","",5,0,5,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(1,234);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(2,460);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(3,2098);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(4,2359);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(5,175);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(1,774.7351);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(2,1537.779);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(3,7059.131);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(4,7905.543);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(5,584.2403);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(1,51.26529);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(2,72.82937);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(3,156.3694);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(4,165.6227);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(5,45.02197);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetEntries(5326);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206901");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206906");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206940");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"207099");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"207100");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.925358e-316,7.291122e-304,2.361871e-310,1.5,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
