{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:54:56 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMProf","",5,0,5,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(1,237);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(2,482);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(3,2143);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(4,2409);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(5,176);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(1,790.9672);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(2,1618.061);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(3,7238.458);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(4,8117.268);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(5,600.2508);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(1,51.49114);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(2,73.92901);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(3,156.7938);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(4,165.8269);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(5,45.3438);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetEntries(5447);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206901");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206906");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206940");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"207099");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"207100");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.491518e-316,2.361872e-310,6.732347e-316,7.181605e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
