{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:33:11 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",6,0,6,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(1,18);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,7);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(1,67.03834);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,30.65046);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,27.8208);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,7.281962);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,32.05666);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(1,16.07521);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,10.85567);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,10.80428);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,5.157904);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,10.76458);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(44);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.597853e-314,1.627223e-314,2.318093e-310,1.619149e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
