{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:32:07 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(1,1529);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(2,467);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(3,914);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(4,502);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(5,458);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(6,486);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(1,4395.459);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(2,1345.613);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(3,2629.902);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(4,1430.331);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(5,1301.055);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(6,1402.7);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(1,113.8829);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(2,63.00458);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(3,88.34134);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(4,64.66914);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(5,61.65652);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(6,64.91203);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetEntries(4356);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.627184e-314,2.318094e-310,1.601364e-314,1.627223e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("e");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
