{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:31:10 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,367);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,71);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,229);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,73);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,80);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,127);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,1234.497);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,235.7503);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,768.5327);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,240.3993);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,259.7853);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,422.6593);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,65.54829);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,28.45175);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,51.71338);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,28.70739);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,29.58346);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,38.14348);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(947);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.601365e-314,7.291122e-304,2.318093e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
