{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:33:02 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",6,0,6,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(1,17);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(1,53.59039);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,2.968584);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,25.3361);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,28.75905);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,12.40162);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,19.60483);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(1,13.10804);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,2.968584);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,8.983629);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,9.617191);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,6.202423);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,8.027049);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(45);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.627184e-314,2.318094e-310,1.601365e-314,1.601365e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
