{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:30:10 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(1,73312);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(2,17960);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(3,45762);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(4,17966);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(5,21088);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(6,26670);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(1,209328.6);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(2,51199.42);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(3,130708.2);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(4,51051.18);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(5,60044.24);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(6,76283.74);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(1,783.0481);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(2,387.2112);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(3,619.0565);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(4,385.9993);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(5,418.982);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(6,473.2025);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetEntries(202758);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.630479e-314,7.291122e-304,2.318093e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("c");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
