{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:34:06 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMSProf","",6,0,6,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(1,2647);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(2,625);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(3,1613);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(4,636);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(5,731);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(6,910);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(1,9108.217);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(2,2133.46);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(3,5567.705);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(4,2176.085);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(5,2512.687);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(6,3131.193);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(1,177.4447);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(2,85.5396);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(3,138.9452);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(4,86.52213);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(5,93.1514);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(6,104.0346);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetEntries(7162);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.606261e-314,2.318094e-310,1.627224e-314,1.597858e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
