{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:34:03 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMProf","",6,0,6,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(1,2647);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(2,625);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(3,1613);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(4,636);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(5,731);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(6,910);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(1,8927.704);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(2,2089.164);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(3,5469.048);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(4,2124.699);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(5,2465.282);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(6,3078.363);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(1,173.9956);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(2,83.77248);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(3,136.5259);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(4,84.51981);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(5,91.4145);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(6,102.2775);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetEntries(7162);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.627184e-314,2.318094e-310,2.318093e-310,1.671506e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
