{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:33:05 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",6,0,6,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(1,17);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(1,56.66624);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,3.204857);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,27.14926);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,29.84558);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,12.82308);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,20.57596);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(1,13.75901);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,3.204857);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,9.625057);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,9.982577);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,6.416193);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,8.44604);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(45);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.671509e-314,7.291122e-304,2.318093e-310,9.487443e-311,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
