{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 12:32:04 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMSProf","",6,0,6,"");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(1,2111);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(2,695);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(3,1224);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(4,783);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(5,670);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(6,653);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(1,6990.098);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(2,2280.367);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(3,4045.312);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(4,2575.873);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(5,2218.455);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(6,2164.223);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(1,152.4207);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(2,86.64974);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(3,115.8213);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(4,92.22526);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(5,85.89276);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(6,84.83821);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetEntries(6136);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.597859e-314,2.318094e-310,1.59782e-314,1.601364e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("d");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
