{
//=========Macro generated from canvas: c1/c1,
//=========  (Tue Mar 18 15:16:57 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1,",0,0,1200,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-0.4090909,0.01240506,4.136364,0.06303797);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxProf = new TProfile("HSCPHLTTriggerMuFilterdEdxProf","",4,0,4,"");
   HSCPHLTTriggerMuFilterdEdxProf->SetBinEntries(1,439);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinEntries(2,6);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinEntries(3,12109);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinEntries(4,10480);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinContent(1,18.70161);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinContent(2,0.1751716);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinContent(3,458.1504);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinContent(4,398.041);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinError(1,1.206846);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinError(2,0.09557065);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinError(3,5.629419);
   HSCPHLTTriggerMuFilterdEdxProf->SetBinError(4,5.298926);
   HSCPHLTTriggerMuFilterdEdxProf->SetMinimum(0.02);
   HSCPHLTTriggerMuFilterdEdxProf->SetMaximum(0.06);
   HSCPHLTTriggerMuFilterdEdxProf->SetEntries(23034);
   HSCPHLTTriggerMuFilterdEdxProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxProf->SetLineWidth(2);
   HSCPHLTTriggerMuFilterdEdxProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxProf->SetMarkerSize(0.5);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetBinLabel(1,"190645");
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetBinLabel(2,"");
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetBinLabel(3,"");
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetBinLabel(4,"190738");
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetTitleSize(0.05);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetTitle("I_{as}");
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxProf->Draw("E1");
   
   TLegend *leg = new TLegend(0.59,0.87,0.79,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(20);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("HSCPHLTTriggerMuFilterdEdxProf","SingleMu40","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.945,0.82,0.995,0.945,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
