{
//=========Macro generated from canvas: c1/c1,
//=========  (Tue Mar 18 15:16:57 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1,",0,0,1200,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-0.4090909,11.99635,4.136364,18.3398);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterNVertProf = new TProfile("HSCPHLTTriggerMuFilterNVertProf","",4,0,4,"");
   HSCPHLTTriggerMuFilterNVertProf->SetBinEntries(1,439);
   HSCPHLTTriggerMuFilterNVertProf->SetBinEntries(2,6);
   HSCPHLTTriggerMuFilterNVertProf->SetBinEntries(3,12109);
   HSCPHLTTriggerMuFilterNVertProf->SetBinEntries(4,10480);
   HSCPHLTTriggerMuFilterNVertProf->SetBinContent(1,7692);
   HSCPHLTTriggerMuFilterNVertProf->SetBinContent(2,89);
   HSCPHLTTriggerMuFilterNVertProf->SetBinContent(3,169328);
   HSCPHLTTriggerMuFilterNVertProf->SetBinContent(4,138441);
   HSCPHLTTriggerMuFilterNVertProf->SetBinError(1,377.3619);
   HSCPHLTTriggerMuFilterNVertProf->SetBinError(2,37.48333);
   HSCPHLTTriggerMuFilterNVertProf->SetBinError(3,1591.027);
   HSCPHLTTriggerMuFilterNVertProf->SetBinError(4,1400.861);
   HSCPHLTTriggerMuFilterNVertProf->SetEntries(23034);
   HSCPHLTTriggerMuFilterNVertProf->SetStats(0);
   HSCPHLTTriggerMuFilterNVertProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterNVertProf->SetLineWidth(2);
   HSCPHLTTriggerMuFilterNVertProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterNVertProf->SetMarkerSize(0.5);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetBinLabel(1,"190645");
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetBinLabel(2,"");
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetBinLabel(3,"");
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetBinLabel(4,"190738");
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetTitleSize(0.05);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterNVertProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetTitle("<#Reco Vertices>");
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterNVertProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterNVertProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterNVertProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterNVertProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterNVertProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterNVertProf->Draw("E1");
   
   TLegend *leg = new TLegend(0.59,0.87,0.79,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(20);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("HSCPHLTTriggerMuFilterNVertProf","SingleMu40","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.945,0.82,0.995,0.945,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
