{
//=========Macro generated from canvas: c1/c1,
//=========  (Tue Mar 18 15:16:57 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1,",0,0,1200,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-0.4090909,49.98181,4.136364,62.69349);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterPtProf = new TProfile("HSCPHLTTriggerMuFilterPtProf","",4,0,4,"");
   HSCPHLTTriggerMuFilterPtProf->SetBinEntries(1,439);
   HSCPHLTTriggerMuFilterPtProf->SetBinEntries(2,6);
   HSCPHLTTriggerMuFilterPtProf->SetBinEntries(3,12109);
   HSCPHLTTriggerMuFilterPtProf->SetBinEntries(4,10480);
   HSCPHLTTriggerMuFilterPtProf->SetBinContent(1,26534.15);
   HSCPHLTTriggerMuFilterPtProf->SetBinContent(2,338.0635);
   HSCPHLTTriggerMuFilterPtProf->SetBinContent(3,726620.8);
   HSCPHLTTriggerMuFilterPtProf->SetBinContent(4,627044.9);
   HSCPHLTTriggerMuFilterPtProf->SetBinError(1,1341.83);
   HSCPHLTTriggerMuFilterPtProf->SetBinError(2,140.085);
   HSCPHLTTriggerMuFilterPtProf->SetBinError(3,6996.308);
   HSCPHLTTriggerMuFilterPtProf->SetBinError(4,6469.809);
   HSCPHLTTriggerMuFilterPtProf->SetEntries(23034);
   HSCPHLTTriggerMuFilterPtProf->SetStats(0);
   HSCPHLTTriggerMuFilterPtProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterPtProf->SetLineWidth(2);
   HSCPHLTTriggerMuFilterPtProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterPtProf->SetMarkerSize(0.5);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetBinLabel(1,"190645");
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetBinLabel(2,"");
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetBinLabel(3,"");
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetBinLabel(4,"190738");
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetTitleSize(0.05);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterPtProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetTitle("p_{T} (GeV/c)");
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterPtProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterPtProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterPtProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterPtProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterPtProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterPtProf->Draw("E1");
   
   TLegend *leg = new TLegend(0.59,0.87,0.79,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(20);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("HSCPHLTTriggerMuFilterPtProf","SingleMu40","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.945,0.82,0.995,0.945,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
