{
//=========Macro generated from canvas: c1/c1,
//=========  (Tue Mar 18 15:16:57 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1,",0,0,1200,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0.4929858,2.667089,0.8471947,3.553165);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TGraphErrors *gre = new TGraphErrors(4);
   gre->SetName("Graph");
   gre->SetTitle("");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(26);
   gre->SetPoint(0,0.5508399,3.057395);
   gre->SetPointError(0,0,0.0443171);
   gre->SetPoint(1,0.5797014,2.998655);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,0.7240087,3.106314);
   gre->SetPointError(2,0,0.0087908);
   gre->SetPoint(3,0.8105931,3.12936);
   gre->SetPointError(3,0,0.009983547);
   
   TH1F *Graph_Graph6 = new TH1F("Graph_Graph6","",100,0.5248646,0.8365684);
   Graph_Graph6->SetMinimum(2.8);
   Graph_Graph6->SetMaximum(3.5);
   Graph_Graph6->SetDirectory(0);
   Graph_Graph6->SetStats(0);
   Graph_Graph6->SetLineStyle(0);
   Graph_Graph6->SetMarkerStyle(20);
   Graph_Graph6->GetXaxis()->SetTitle("Int. Luminosity (/pb)");
   Graph_Graph6->GetXaxis()->SetLabelFont(42);
   Graph_Graph6->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph6->GetXaxis()->SetTitleFont(42);
   Graph_Graph6->GetYaxis()->SetTitle("I_{h} (MeV/cm)");
   Graph_Graph6->GetYaxis()->SetLabelFont(42);
   Graph_Graph6->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetYaxis()->SetTitleOffset(1.1);
   Graph_Graph6->GetYaxis()->SetTitleFont(42);
   Graph_Graph6->GetZaxis()->SetLabelFont(42);
   Graph_Graph6->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph6);
   
   gre->Draw("ap");
   
   gre = new TGraphErrors(4);
   gre->SetName("Graph");
   gre->SetTitle("");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(32);
   gre->SetPoint(0,0.5508399,3.0213);
   gre->SetPointError(0,0,0.05495508);
   gre->SetPoint(1,0.5797014,3.174117);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,0.7240087,3.037144);
   gre->SetPointError(2,0,0.00905764);
   gre->SetPoint(3,0.8105931,3.037698);
   gre->SetPointError(3,0,0.009774493);
   
   TH1F *Graph_Graph7 = new TH1F("Graph_Graph7","",100,0.5248646,0.8365684);
   Graph_Graph7->SetMinimum(2.8);
   Graph_Graph7->SetMaximum(3.5);
   Graph_Graph7->SetDirectory(0);
   Graph_Graph7->SetStats(0);
   Graph_Graph7->SetLineStyle(0);
   Graph_Graph7->SetMarkerStyle(20);
   Graph_Graph7->GetXaxis()->SetTitle("Int. Luminosity (/pb)");
   Graph_Graph7->GetXaxis()->SetLabelFont(42);
   Graph_Graph7->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph7->GetXaxis()->SetTitleOffset(1.1);
   Graph_Graph7->GetXaxis()->SetTitleFont(42);
   Graph_Graph7->GetYaxis()->SetTitle("I_{h} (MeV/cm)");
   Graph_Graph7->GetYaxis()->SetLabelFont(42);
   Graph_Graph7->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph7->GetYaxis()->SetTitleOffset(1.1);
   Graph_Graph7->GetYaxis()->SetTitleFont(42);
   Graph_Graph7->GetZaxis()->SetLabelFont(42);
   Graph_Graph7->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph7->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph7);
   
   gre->Draw("p");
   
   TF1 *FitgraphPC = new TF1("FitgraphPC","pol1",250,5000);
   FitgraphPC->SetFillColor(19);
   FitgraphPC->SetFillStyle(0);
   FitgraphPC->SetMarkerStyle(20);
   FitgraphPC->SetLineColor(2);
   FitgraphPC->SetLineWidth(2);
   FitgraphPC->GetXaxis()->SetNdivisions(505);
   FitgraphPC->GetXaxis()->SetLabelFont(42);
   FitgraphPC->GetXaxis()->SetLabelOffset(0.007);
   FitgraphPC->GetXaxis()->SetLabelSize(0.05);
   FitgraphPC->GetXaxis()->SetTitleOffset(1.1);
   FitgraphPC->GetXaxis()->SetTitleFont(42);
   FitgraphPC->GetYaxis()->SetLabelFont(42);
   FitgraphPC->GetYaxis()->SetLabelOffset(0.007);
   FitgraphPC->GetYaxis()->SetLabelSize(0.05);
   FitgraphPC->GetYaxis()->SetTitleOffset(1.35);
   FitgraphPC->GetYaxis()->SetTitleFont(42);
   FitgraphPC->SetParameter(0,0);
   FitgraphPC->SetParError(0,0);
   FitgraphPC->SetParLimits(0,0,0);
   FitgraphPC->SetParameter(1,0);
   FitgraphPC->SetParError(1,0);
   FitgraphPC->SetParLimits(1,0,0);
   FitgraphPC->Draw("same");
   
   TF1 *FitgraphPF = new TF1("FitgraphPF","pol1",250,5000);
   FitgraphPF->SetFillColor(19);
   FitgraphPF->SetFillStyle(0);
   FitgraphPF->SetMarkerStyle(20);
   FitgraphPF->SetLineColor(4);
   FitgraphPF->SetLineWidth(2);
   FitgraphPF->GetXaxis()->SetNdivisions(505);
   FitgraphPF->GetXaxis()->SetLabelFont(42);
   FitgraphPF->GetXaxis()->SetLabelOffset(0.007);
   FitgraphPF->GetXaxis()->SetLabelSize(0.05);
   FitgraphPF->GetXaxis()->SetTitleOffset(1.1);
   FitgraphPF->GetXaxis()->SetTitleFont(42);
   FitgraphPF->GetYaxis()->SetLabelFont(42);
   FitgraphPF->GetYaxis()->SetLabelOffset(0.007);
   FitgraphPF->GetYaxis()->SetLabelSize(0.05);
   FitgraphPF->GetYaxis()->SetTitleOffset(1.35);
   FitgraphPF->GetYaxis()->SetTitleFont(42);
   FitgraphPF->SetParameter(0,0);
   FitgraphPF->SetParError(0,0);
   FitgraphPF->SetParLimits(0,0,0);
   FitgraphPF->SetParameter(1,0);
   FitgraphPF->SetParError(1,0);
   FitgraphPF->SetParLimits(1,0,0);
   FitgraphPF->Draw("same");
   
   TLegend *leg = new TLegend(0.59,0.77,0.79,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","dE/dx (Pixel) |#eta|<0.5","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","dE/dx (Pixel) |#eta|>1.5","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(32);
   entry->SetMarkerSize(1);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
