{
//=========Macro generated from canvas: c1/c1,
//=========  (Tue Mar 18 15:16:55 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1,",0,0,1200,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-0.3111111,3.005063,4.133333,3.637975);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *AnydEdxMSProf = new TProfile("AnydEdxMSProf","",4,0,4,"");
   AnydEdxMSProf->SetBinEntries(1,441);
   AnydEdxMSProf->SetBinEntries(2,6);
   AnydEdxMSProf->SetBinEntries(3,12134);
   AnydEdxMSProf->SetBinEntries(4,10505);
   AnydEdxMSProf->SetBinContent(1,1482.089);
   AnydEdxMSProf->SetBinContent(2,19.48135);
   AnydEdxMSProf->SetBinContent(3,40472.04);
   AnydEdxMSProf->SetBinContent(4,35041.16);
   AnydEdxMSProf->SetBinError(1,70.71339);
   AnydEdxMSProf->SetBinError(2,7.965665);
   AnydEdxMSProf->SetBinError(3,368.1013);
   AnydEdxMSProf->SetBinError(4,342.5299);
   AnydEdxMSProf->SetMinimum(3.1);
   AnydEdxMSProf->SetMaximum(3.6);
   AnydEdxMSProf->SetEntries(23086);
   AnydEdxMSProf->SetStats(0);
   AnydEdxMSProf->SetLineStyle(0);
   AnydEdxMSProf->SetLineWidth(2);
   AnydEdxMSProf->SetMarkerStyle(20);
   AnydEdxMSProf->SetMarkerSize(0.5);
   AnydEdxMSProf->GetXaxis()->SetBinLabel(1,"190645");
   AnydEdxMSProf->GetXaxis()->SetBinLabel(2,"");
   AnydEdxMSProf->GetXaxis()->SetBinLabel(3,"");
   AnydEdxMSProf->GetXaxis()->SetBinLabel(4,"190738");
   AnydEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   AnydEdxMSProf->GetXaxis()->SetNdivisions(505);
   AnydEdxMSProf->GetXaxis()->SetLabelFont(42);
   AnydEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   AnydEdxMSProf->GetXaxis()->SetLabelSize(0.05);
   AnydEdxMSProf->GetXaxis()->SetTitleSize(0.05);
   AnydEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   AnydEdxMSProf->GetXaxis()->SetTitleFont(42);
   AnydEdxMSProf->GetYaxis()->SetTitle("I_{h} S");
   AnydEdxMSProf->GetYaxis()->SetNdivisions(505);
   AnydEdxMSProf->GetYaxis()->SetLabelFont(42);
   AnydEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   AnydEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   AnydEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   AnydEdxMSProf->GetYaxis()->SetTitleFont(42);
   AnydEdxMSProf->GetZaxis()->SetLabelFont(42);
   AnydEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   AnydEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   AnydEdxMSProf->GetZaxis()->SetTitleFont(42);
   AnydEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(0.945,0.82,0.995,0.945,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("Ђявя");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
