{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:38:43 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,14);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(10,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,5);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,16);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,29.17891);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,49.39995);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,27.37246);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(10,3.875828);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,19.38879);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,58.77074);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,10.41052);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,13.23046);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,9.750192);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(10,3.875828);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,8.716696);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,14.84426);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(52);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"193093");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"193112");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"193123");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"193124");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"193207");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"193334");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"193336");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"193541");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"193556");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"193557");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"193575");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"193621");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.458131e-316,2.364969e-310,7.20409e-316,8.449944e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
