{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:38:39 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,18);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,3.689674);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,3.408192);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,23.71784);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,54.60278);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,29.97703);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,3.021338);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,20.36161);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,60.03413);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,3.689674);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,3.408192);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,8.981845);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,13.68063);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,10.00197);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,3.021338);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,8.322202);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,14.1712);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(59);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"193093");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"193112");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"193123");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"193124");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"193207");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"193334");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"193336");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"193541");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"193556");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"193557");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"193575");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"193621");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.419649e-316,7.291122e-304,2.364968e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
