{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:40:28 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(6,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,13.80821);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,19.41598);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,3.818301);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,31.09857);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(6,14.18057);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,3.592433);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,14.16654);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,13.2233);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,18.29177);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,6.918839);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,7.934669);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,3.818301);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,10.42456);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(6,7.136161);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,3.592433);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,7.099016);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,6.634794);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,8.273266);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(38);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208390");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208391");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208427");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208428");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208429");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208487");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"208509");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"208538");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"208540");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"208541");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"208551");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"208686");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.775777e-316,7.291122e-304,2.357704e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
