{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:40:24 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(1,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(1,6.108289);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,33.37186);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,37.89764);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,15.92948);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,51.56465);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,19.30237);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,6.283863);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,19.23373);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,37.25282);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,21.68489);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(1,4.322622);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,10.10209);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,10.9806);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,7.126904);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,12.9076);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,7.895265);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,4.462873);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,7.868776);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,10.83802);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,8.217604);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(79);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208390");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208391");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208427");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208428");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208429");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208487");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"208509");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"208538");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"208540");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"208541");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"208551");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"208686");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.927423e-316,7.291122e-304,2.357704e-310,6.938838e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
