{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:17:58 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",8,0,8,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,3638);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,37851);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,117016);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,72123);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(5,21576);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(6,716);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(7,47482);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(8,11958);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,12112.68);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,124808.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,388163.3);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,237603.7);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(5,71403.89);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(6,2381.411);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(7,157436.2);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(8,39337.8);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,201.2008);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,642.712);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,1136.841);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,886.3681);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(5,487.0127);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(6,89.17675);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(7,723.8351);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(8,360.4184);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(312360);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.610985e-316,2.347714e-310,9.390587e-316,6.649722e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
