{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:18:00 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(1,1009);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(2,9631);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(3,30894);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(4,18126);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(5,5534);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(6,191);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(7,12323);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(8,2968);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(1,3402.735);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(2,32451.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(3,104211.3);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(4,61266.56);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(5,18674.99);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(6,647.0084);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(7,41539);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(8,10047.49);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(1,107.9324);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(2,333.0216);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(3,597.1619);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(4,458.3707);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(5,252.8503);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(6,47.12492);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(7,376.7441);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(8,186.0613);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetEntries(80676);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.468948e-316,2.347714e-310,6.692575e-316,8.468929e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("c");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
