{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:20:45 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(1,75);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(2,716);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(3,2527);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(4,1376);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(5,467);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(6,22);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(7,936);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(8,205);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(1,273.5226);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(2,2579.542);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(3,9105.529);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(4,4975.192);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(5,1696.517);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(6,83.69895);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(7,3386.146);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(8,734.2859);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(1,32.21346);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(2,97.47854);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(3,183.1796);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(4,135.686);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(5,79.50545);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(6,18.06421);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(7,111.8682);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(8,51.89743);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetEntries(6324);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.610986e-316,2.347714e-310,2.347712e-310,6.488769e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
