{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:19:12 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMProf","",8,0,8,"");
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(1,51);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(2,967);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(3,2140);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(4,1843);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(5,446);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(6,7);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(7,812);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(8,341);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(1,163.3475);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(2,2977.06);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(3,6679.106);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(4,5693.273);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(5,1382.89);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(6,22.50152);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(7,2544.667);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(8,1051.702);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(1,22.91753);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(2,96.16704);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(3,144.9229);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(4,133.0745);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(5,65.69329);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(6,8.528306);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(7,89.56988);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(8,57.13);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetEntries(6607);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.703977e-316,2.347714e-310,6.559531e-316,6.536898e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
