{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:20:02 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,15);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,14.0043);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,54.0216);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,18.45915);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,3.34106);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,22.73134);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,3.459965);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,7.079211);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,14.25816);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,8.40997);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,3.34106);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,9.359574);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,3.459965);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(32);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.610948e-316,2.347714e-310,8.469024e-316,9.734053e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
