{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:18:02 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFiltermyHist = new TProfile("HSCPHLTTriggerMuFiltermyHist","",8,0,8,"");
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(1,2734);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(2,28646);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(3,87318);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(4,54210);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(5,15934);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(6,508);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(7,35048);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(8,9099);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(1,9682.569);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(2,100357.1);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(3,307960.1);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(4,190184.6);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(5,56126.07);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(6,1799.329);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(7,123631.9);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(8,31840.53);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(1,186.8646);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(2,598.1072);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(3,1051.495);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(4,824.07);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(5,448.6013);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(6,80.58062);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(7,666.0892);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(8,336.8995);
   HSCPHLTTriggerMuFiltermyHist->SetEntries(233497);
   HSCPHLTTriggerMuFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.295511e-316,7.291122e-304,2.347712e-310,9.237753e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
