{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:20:47 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMuDeDxFiltermyHist","",8,0,8,"");
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(1,94);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(2,967);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(3,3236);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(4,1825);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(5,605);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(6,23);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(7,1215);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(8,288);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(1,387.2049);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(2,3869.952);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(3,13081.35);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(4,7330.391);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(5,2455.488);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(6,101.5841);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(7,4921.548);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(8,1137.487);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(1,40.83584);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(2,126.2918);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(3,233.3822);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(4,174.2317);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(5,101.4697);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(6,21.51951);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(7,143.2343);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(8,68.06264);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetEntries(8253);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.513813e-316,7.076786e-316,7.076682e-316,6.513814e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
