{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:20:42 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMSProf","",8,0,8,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(1,96);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(2,922);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(3,3261);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(4,1739);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(5,602);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(6,22);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(7,1233);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(8,264);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(1,334.8678);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(2,3163.519);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(3,11268.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(4,5963.325);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(5,2066.769);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(6,78.33378);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(7,4277.674);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(8,901.4715);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(1,34.25457);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(2,104.4226);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(3,197.7693);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(4,143.3395);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(5,84.42548);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(6,16.76305);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(7,122.1018);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(8,55.62732);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetEntries(8139);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.039079e-315,7.291122e-304,2.347712e-310,1.5,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
