{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:18:36 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,11);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,110);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,334);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,219);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,43);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(7,111);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(8,41);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,40.29105);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,398.7891);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,1192.777);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,789.9907);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,159.1278);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,14.68605);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(7,406.66);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(8,144.834);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,12.41382);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,38.49255);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,65.82672);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,54.01881);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,24.49461);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,7.462773);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(7,39.04781);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(8,22.75834);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(873);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.704027e-316,2.347714e-310,7.00253e-316,1.03908e-315,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
