{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:18:33 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMProf","",8,0,8,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(1,15);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(2,154);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(3,493);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(4,305);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(5,78);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(6,7);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(7,182);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(8,50);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(1,49.43724);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(2,512.9243);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(3,1641.889);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(4,1005.462);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(5,253.0954);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(6,23.59281);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(7,605.2055);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(8,166.6804);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(1,12.78042);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(2,41.47749);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(3,74.21311);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(4,57.84374);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(5,28.77989);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(6,8.935747);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(7,45.01687);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(8,23.65246);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetEntries(1284);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.612926e-316,7.291122e-304,2.347712e-310,7.398621e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
