{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:17:57 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMProf","",8,0,8,"");
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(1,3638);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(2,37851);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(3,117016);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(4,72123);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(5,21576);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(6,716);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(7,47482);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(8,11958);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(1,11419.69);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(2,116692.6);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(3,365297.4);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(4,222224.6);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(5,67076.57);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(6,2231.64);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(7,148247.4);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(8,36677.9);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(1,189.9047);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(2,601.9034);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(3,1071.181);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(4,830.3303);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(5,458.0438);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(6,83.68726);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(7,682.3631);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(8,336.6324);
   HSCPHLTTriggerMuFilterdEdxMProf->SetEntries(312360);
   HSCPHLTTriggerMuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.704014e-316,2.347714e-310,2.347712e-310,9.966283e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
