{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 10:53:17 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,21);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(9,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,10.93076);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,3.125705);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,27.44613);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,6.282557);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,77.9179);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(9,22.97541);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,6.148504);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,29.11115);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,6.336253);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,3.125705);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,9.732667);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,4.445239);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,17.2231);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(9,9.485573);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,4.347838);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,10.32822);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(51);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"207882");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"207883");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"207884");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"207885");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"207886");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"207889");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"207898");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"207905");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"207920");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"207921");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"207922");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"207924");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.051627e-315,2.339779e-310,9.650748e-316,9.650757e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
