{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 10:53:12 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,28);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(9,10);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,5.721476);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,6.654963);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,6.310287);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,34.86836);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,2.980863);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,89.97008);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(9,31.17407);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,5.785442);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,11.50732);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,18.72856);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,4.045696);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,4.717576);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,4.462063);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,10.5291);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,2.980863);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,17.08199);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(9,9.928095);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,4.095878);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,5.765759);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,7.662515);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(68);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"207882");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"207883");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"207884");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"207885");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"207886");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"207889");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"207898");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"207905");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"207920");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"207921");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"207922");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"207924");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.711333e-316,7.291122e-304,2.339778e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("À");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
