{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 17:38:12 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,32);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(10,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,22);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,6.376567);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,7.037804);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,14.09203);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,3.600875);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,111.9294);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(10,38.41225);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,90.88596);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,33.25386);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,4.514971);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,4.977008);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,7.06113);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,3.600875);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,19.93737);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(10,12.32094);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,21.57906);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,11.16671);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(82);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"198116");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"198207");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"198208");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"198210");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"198212");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"198213");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"198215");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"198230");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"198249");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"198269");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"198271");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"198272");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.433948e-316,2.331184e-310,2.331182e-310,6.229736e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
