{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:57:31 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMSProf","",5,0,5,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(1,54);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(2,22);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(3,4);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(4,897);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(5,175);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(1,185.6479);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(2,76.3959);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(3,14.37064);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(4,3082.035);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(5,606.3177);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(1,25.31865);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(2,16.32715);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(3,7.218956);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(4,103.1149);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(5,45.92354);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetEntries(1152);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"193834");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"193835");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"193836");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"193998");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"193999");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.343259e-316,7.291122e-304,2.355455e-310,1.987532e-14,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
