{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:03:33 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFiltermyHist = new TProfile("HSCPHLTTriggerMuFiltermyHist","",6,0,6,"");
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(1,73761);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(2,19960);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(3,45831);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(4,19899);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(5,21317);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(6,26258);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(1,259426.2);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(2,69974.77);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(3,161251.9);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(4,69574.25);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(5,74901.78);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(6,92470.63);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(1,963.5939);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(2,499.7725);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(3,760.0145);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(4,497.4927);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(5,517.6012);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(6,575.7773);
   HSCPHLTTriggerMuFiltermyHist->SetEntries(207026);
   HSCPHLTTriggerMuFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.783211e-316,7.291122e-304,2.347554e-310,7.910211e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
