{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:04:27 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMSProf","",6,0,6,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(1,401);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(2,78);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(3,237);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(4,82);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(5,87);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(6,135);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(1,1361.782);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(2,264.3401);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(3,812.7398);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(4,275.3911);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(5,297.9745);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(6,461.8509);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(1,68.14909);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(2,29.99337);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(3,52.91434);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(4,30.47438);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(5,32.0202);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(6,39.8463);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetEntries(1020);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.296209e-316,2.347555e-310,2.347554e-310,4.24166e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
