{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:05:19 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMProf","",6,0,6,"");
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(1,2111);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(2,695);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(3,1224);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(4,783);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(5,670);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(6,653);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(1,6541.214);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(2,2133.916);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(3,3796.466);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(4,2394.822);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(5,2066.797);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(6,2028.195);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(1,142.874);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(2,81.22528);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(3,108.8858);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(4,85.91202);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(5,80.11164);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(6,79.58938);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetEntries(6136);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.525466e-316,2.347555e-310,2.347554e-310,6.524386e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
