{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:04:33 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMetDeDxFiltermyHist","",6,0,6,"");
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(1,391);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(2,77);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(3,237);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(4,86);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(5,84);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(6,134);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(1,1564.118);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(2,300.2995);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(3,944.7361);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(4,333.1455);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(5,336.1448);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(6,530.1638);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(1,80.35953);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(2,34.71523);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(3,62.37057);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(4,36.48871);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(5,37.23769);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(6,46.49963);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetEntries(1009);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.939562e-316,2.347555e-310,2.347554e-310,7.657654e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
