{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:03:29 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(1,25531);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(2,6649);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(3,15890);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(4,6554);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(5,7258);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(6,9121);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(1,86157.04);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(2,22471.42);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(3,53639.73);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(4,22095.49);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(5,24529.39);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(6,30790.2);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(1,542.9654);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(2,277.8129);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(3,428.7123);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(4,274.98);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(5,290.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(6,324.746);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetEntries(71003);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.786633e-316,2.347555e-310,7.657579e-316,5.296249e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("c");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
