{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:04:30 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,280);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,56);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,183);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,51);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,58);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,88);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,1014.162);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,197.6231);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,658.1684);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,185.773);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,211.029);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,319.5779);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,61.26555);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,26.71438);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,49.28591);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,26.30421);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,28.08123);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,34.42141);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(716);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.296209e-316,2.347555e-310,5.296243e-316,5.939602e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
