{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:07:30 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMPProf","",6,0,6,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(1,1999);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(2,457);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(3,1268);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(4,468);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(5,568);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(6,716);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(1,7173.793);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(2,1655.847);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(3,4569.141);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(4,1685.992);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(5,2041.266);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(6,2556.659);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(1,162.0251);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(2,78.27578);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(3,129.8953);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(4,78.77925);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(5,86.46105);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(6,96.44454);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetEntries(5476);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.550651e-316,2.347555e-310,2.347554e-310,5.293981e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
