{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:05:31 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFiltermyHist = new TProfile("HSCPHLTTriggerL2MuFiltermyHist","",6,0,6,"");
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(1,1610);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(2,564);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(3,951);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(4,582);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(5,487);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(6,510);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(1,5690.243);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(2,1980.249);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(3,3371.387);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(4,2030.361);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(5,1717.053);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(6,1809.784);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(1,143.1171);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(2,84.06185);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(3,110.5461);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(4,84.84602);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(5,78.49402);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(6,81.37776);
   HSCPHLTTriggerL2MuFiltermyHist->SetEntries(4704);
   HSCPHLTTriggerL2MuFiltermyHist->SetStats(0);
   HSCPHLTTriggerL2MuFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerL2MuFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerL2MuFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.525096e-316,7.291122e-304,2.347554e-310,7.910211e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
