{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:03:21 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMProf","",6,0,6,"");
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(1,101251);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(2,26458);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(3,62704);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(4,26582);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(5,29546);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(6,35982);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(1,313951.2);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(2,81278.05);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(3,194713.8);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(4,81594.54);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(5,91405.21);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(6,111965.2);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(1,989.8938);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(2,501.499);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(3,780.1057);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(4,502.2535);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(5,533.5126);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(6,592.0625);
   HSCPHLTTriggerMuFilterdEdxMProf->SetEntries(282523);
   HSCPHLTTriggerMuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.786633e-316,2.347555e-310,5.240901e-316,7.657544e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
