{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:07:33 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMuDeDxFiltermyHist","",6,0,6,"");
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(1,2639);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(2,645);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(3,1642);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(4,678);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(5,746);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(6,912);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(1,10572.07);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(2,2563.097);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(3,6607.414);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(4,2674.776);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(5,2993.464);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(6,3667.368);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(1,208.5793);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(2,102.4125);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(3,165.604);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(4,104.2522);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(5,111.0539);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(6,122.9898);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetEntries(7262);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.297188e-316,5.296832e-316,5.29732e-316,5.297189e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
