{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:03:25 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",6,0,6,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,101251);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,26458);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,62704);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,26582);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(5,29546);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(6,35982);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,334883.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,87121.03);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,207616.8);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,87466.95);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(5,97622.72);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(6,119176.5);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,1054.384);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,536.6107);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,830.6548);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,537.4921);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(5,568.9809);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(6,629.4128);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(282523);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.296246e-316,2.347555e-310,2.347554e-310,7.783932e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
