{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:04:23 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMProf","",6,0,6,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(1,401);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(2,78);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(3,237);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(4,82);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(5,87);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(6,135);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(1,1325.199);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(2,255.4623);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(3,792.8129);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(4,265.2134);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(5,289.8043);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(6,449.4007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(1,66.43554);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(2,29.0509);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(3,51.68892);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(4,29.39757);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(5,31.16704);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(6,38.82995);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetEntries(1020);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"208307");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"208339");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"208341");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"208351");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"208353");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"208357");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.297132e-316,2.347555e-310,2.347554e-310,5.549775e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
