{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:01:59 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",5,0,5,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,9778);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,17327);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,83159);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,94329);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(5,6587);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,32208.6);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,57268.04);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,275399.3);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,311884.6);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(5,21882.88);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,326.3189);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,435.872);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,956.7926);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,1017.382);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(5,270.1419);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(211180);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"206901");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"206906");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"206940");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"207099");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"207100");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.164332e-316,6.383866e-316,2.364969e-310,7.162254e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
