{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:13:52 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(1,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,15);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,10);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(11,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(1,11.77274);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,54.85684);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,11.53027);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,37.32172);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,3.734329);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,3.073098);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,7.795958);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(11,27.59458);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,19.52653);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(1,7.069205);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,14.36726);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,6.682213);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,12.16897);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,3.734329);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,3.073098);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,5.543661);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(11,9.773978);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,7.98808);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(49);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"203909");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"203912");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"203985");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"203986");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"203987");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"203991");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"203992");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"203994");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"204100");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"204101");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"204113");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"204114");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.985909e-316,2.336559e-310,8.028211e-316,9.379943e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
