{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:13:48 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(1,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,29);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,19);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(9,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,15);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(1,9.798767);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,95.19106);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,7.118655);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,61.24868);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,6.055238);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,6.487034);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(9,2.845205);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,9.871746);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,47.93912);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,29.46866);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(1,5.67365);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,17.72544);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,5.034098);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,14.07214);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,4.285126);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,4.587072);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(9,2.845205);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,5.703);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,12.40014);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,9.838527);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(85);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"203909");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"203912");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"203985");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"203986");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"203987");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"203991");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"203992");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"203994");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"204100");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"204101");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"204113");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"204114");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.018486e-316,9.60765e-316,2.336558e-310,1.203531e-315,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
