{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:13:54 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(1,3);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,29);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,3);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,16);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(10,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(1,13.04377);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,103.9128);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,12.50243);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,60.07579);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,3.830566);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,6.355955);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(10,8.684366);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,36.66532);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,31.45274);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(1,7.809382);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,19.61972);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,7.250809);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,15.44204);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,3.830566);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,4.49866);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(10,6.187587);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,11.63095);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,10.50192);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(75);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"203909");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"203912");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"203985");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"203986");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"203987");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"203991");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"203992");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"203994");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"204100");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"204101");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"204113");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"204114");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.840977e-316,7.291122e-304,2.336558e-310,7.838977e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
