{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:13:50 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(1,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,29);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,19);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(9,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,15);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(1,9.800836);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,97.44732);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,7.03182);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,64.06422);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,6.117972);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,6.689109);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(9,3.059174);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,10.06359);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,50.1585);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,30.28257);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(1,5.682248);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,18.14603);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,4.972248);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,14.72829);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,4.326062);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,4.731144);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(9,3.059174);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,5.818605);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,12.99817);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,10.11758);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(85);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"203909");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"203912");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"203985");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"203986");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"203987");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"203991");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"203992");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"203994");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"204100");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"204101");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"204113");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"204114");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.917917e-316,2.336559e-310,9.379965e-316,5.015064e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
