{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:24:30 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,28);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(9,10);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,6.366856);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,6.815602);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,6.700752);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,36.47967);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,3.117239);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,94.4258);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(9,33.30123);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,6.684423);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,13.01056);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,19.90409);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,4.507212);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,4.827316);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,4.743061);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,11.0132);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,3.117239);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,17.88806);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(9,10.57293);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,4.727149);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,6.508197);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,8.153724);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(68);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"207882");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"207883");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"207884");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"207885");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"207886");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"207889");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"207898");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"207905");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"207920");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"207921");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"207922");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"207924");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.750201e-316,8.635372e-316,2.349651e-310,8.535127e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
