{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 17:49:52 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(10,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(11,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(12,18);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,3.324929);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,3.199323);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,23.49411);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,53.05437);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,29.02843);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(10,3.099);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(11,20.29518);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(12,58.34419);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,3.324929);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,3.199323);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,8.897455);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,13.30589);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,9.693839);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(10,3.099);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(11,8.304793);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(12,13.79538);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(59);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"193093");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"193112");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"193123");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"193124");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"193207");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"193334");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"193336");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"193541");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"193556");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(10,"193557");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(11,"193575");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(12,"193621");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.002642e-316,7.291122e-304,2.317849e-310,2.317644e-310,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
