{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:19:47 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",4,0,4,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,496);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,7);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,13307);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,11558);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,1655.782);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,22.5172);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,44233);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,38401.99);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,74.49686);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,8.524564);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,384.1595);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,357.8699);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(25368);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"190645");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"190704");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"190705");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"190738");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(1.645603e-314,1.629643e-314,2.370219e-310,1.624426e-314,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
