{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:35:40 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(1,732);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(2,89);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(3,5);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(4,412);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(5,269);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(6,217);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(7,104);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(8,107);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(9,475);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(1,2479.043);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(2,298.106);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(3,17.54604);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(4,1403.095);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(5,908.8343);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(6,727.9029);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(7,347.4803);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(8,371.9287);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(9,1595.996);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(1,92.27102);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(2,31.77195);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(3,7.849364);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(4,69.61379);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(5,55.77609);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(6,49.67628);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(7,34.23225);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(8,36.46427);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(9,73.85819);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetEntries(2410);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.675598e-316,7.291122e-304,2.368214e-310,2.368214e-310,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("e");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
