{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:34:38 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,221);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,141);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,101);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,72);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(7,46);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(8,52);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(9,188);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,821.2812);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,72.67615);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,3.610012);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,520.5264);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,369.7121);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,260.4583);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(7,162.9244);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(8,203.867);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(9,687.5628);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,56.16268);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,16.3803);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,3.610012);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,44.29644);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,37.20725);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,31.24212);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(7,24.26298);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(8,28.99492);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(9,50.71891);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(842);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.015425e-316,2.368216e-310,6.027083e-316,9.675682e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
