{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:36:48 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",9,0,9,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(1,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,4);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,5);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(9,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(1,29.77129);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,3.498734);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,13.79194);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,20.1889);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,7.358454);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,6.401322);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,27.99503);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(9,31.54518);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(1,10.62455);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,3.498734);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,6.923724);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,9.180325);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,5.206092);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,4.527119);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,11.83748);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(9,10.58172);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(37);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.946277e-316,7.291122e-304,2.368214e-310,2.025743e-153,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
