{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:34:36 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMSProf","",9,0,9,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(1,239);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(2,20);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(3,1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(4,180);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(5,137);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(6,97);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(7,69);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(8,63);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(9,260);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(1,811.713);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(2,68.49123);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(3,3.11267);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(4,611.5968);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(5,459.5841);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(6,329.7829);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(7,235.8209);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(8,212.3614);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(9,875.6026);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(1,52.648);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(2,15.34804);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(3,3.11267);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(4,45.68525);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(5,39.32825);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(6,33.54045);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(7,28.46851);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(8,26.8131);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(9,54.4344);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetEntries(1066);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.675669e-316,2.368216e-310,7.720948e-316,9.832546e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
