{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:36:46 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(1,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(9,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(1,20.67317);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,3.291271);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,6.648611);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,8.18672);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(6,3.093378);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,20.50823);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(9,10.2456);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(1,8.466072);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,3.291271);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,4.701346);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,5.790454);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(6,3.093378);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,9.441863);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(9,5.92539);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.792478e-316,2.368216e-310,6.875005e-316,6.878194e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
