{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:33:31 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMProf","",9,0,9,"");
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(1,60088);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(2,7679);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(3,685);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(4,43207);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(5,37242);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(6,25879);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(7,17850);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(8,13996);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinEntries(9,70596);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(1,187927.7);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(2,24044.45);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(3,2155.678);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(4,135993.9);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(5,114589.7);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(6,79344.27);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(7,55078.46);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(8,42958.08);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinContent(9,218370.6);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(1,769.0453);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(2,275.1981);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(3,82.58878);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(4,656.1624);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(5,595.7275);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(6,494.8923);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(7,413.594);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(8,364.2915);
   HSCPHLTTriggerMuFilterdEdxMProf->SetBinError(9,824.5059);
   HSCPHLTTriggerMuFilterdEdxMProf->SetEntries(277222);
   HSCPHLTTriggerMuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(5.029977e-316,7.291122e-304,2.368214e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("Q›
");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
