{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:37:51 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMuDeDxFiltermyHist","",9,0,9,"");
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(1,1561);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(2,187);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(3,16);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(4,1107);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(5,896);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(6,605);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(7,448);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(8,340);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinEntries(9,1792);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(1,6161.194);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(2,736.0519);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(3,60.82097);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(4,4390.58);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(5,3583.771);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(6,2442.767);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(7,1775.772);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(8,1366.263);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinContent(9,7187.15);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(1,158.0993);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(2,54.51319);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(3,15.31282);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(4,133.7201);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(5,121.7006);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(6,100.8932);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(7,84.94078);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(8,75.20757);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetBinError(9,172.1567);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetEntries(6952);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.875958e-316,2.368216e-310,9.642953e-316,8.792482e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
