{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:35:38 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMSProf","",9,0,9,"");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(1,1594);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(2,193);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(3,16);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(4,967);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(5,961);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(6,745);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(7,438);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(8,416);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinEntries(9,1623);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(1,5246.934);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(2,632.1673);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(3,54.51438);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(4,3188.987);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(5,3164.546);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(6,2444.704);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(7,1441.786);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(8,1359.175);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinContent(9,5337.477);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(1,131.6992);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(2,45.57084);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(3,13.64837);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(4,102.7266);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(5,102.2928);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(6,89.71365);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(7,69.02034);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(8,66.76175);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetBinError(9,132.7154);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetEntries(6953);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.675581e-316,2.368216e-310,9.675591e-316,6.027045e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("d");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
