{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:52:24 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFiltermyHist = new TProfile("HSCPHLTTriggerL2MuFiltermyHist","",8,0,8,"");
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(1,45);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(2,789);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(3,1639);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(4,1452);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(5,349);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(6,5);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(7,606);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinEntries(8,272);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(1,161.9848);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(2,2784.174);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(3,5796.137);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(4,5114.033);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(5,1228.837);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(6,17.40998);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(7,2137.928);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinContent(8,950.0903);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(1,24.342);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(2,100.3597);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(3,144.6906);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(4,135.4943);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(5,66.37123);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(6,7.815527);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(7,87.67709);
   HSCPHLTTriggerL2MuFiltermyHist->SetBinError(8,58.11698);
   HSCPHLTTriggerL2MuFiltermyHist->SetEntries(5157);
   HSCPHLTTriggerL2MuFiltermyHist->SetStats(0);
   HSCPHLTTriggerL2MuFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerL2MuFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerL2MuFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.392889e-316,2.352069e-310,2.352068e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
