{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:47 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMProf","",8,0,8,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(1,96);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(2,922);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(3,3261);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(4,1739);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(5,602);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(6,22);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(7,1233);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(8,264);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(1,330.3795);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(2,3097.295);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(3,11061.18);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(4,5859.563);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(5,2030.992);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(6,77.41891);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(7,4197.056);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(8,881.7827);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(1,33.78569);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(2,102.291);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(3,194.2575);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(4,140.8621);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(5,82.99587);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(6,16.53499);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(7,119.8191);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(8,54.40657);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetEntries(8139);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.516393e-316,2.352069e-310,8.306098e-316,8.306123e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
