{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:01 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",8,0,8,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(3,37);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,14);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,18);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,27.84194);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(3,119.5899);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,42.86259);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,14.71294);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,56.04683);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,3.170605);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,9.294327);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(3,19.75218);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,11.52744);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,6.627777);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,13.26787);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,3.170605);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(84);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.514283e-316,7.291122e-304,2.352068e-310,9.713726e-319,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
