{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:51:28 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMSProf","",8,0,8,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(1,15);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(2,154);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(3,493);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(4,305);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(5,78);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(6,7);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(7,182);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinEntries(8,50);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(1,49.66575);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(2,526.443);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(3,1688.93);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(4,1035.586);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(5,263.9632);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(6,23.95854);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(7,624.593);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinContent(8,171.349);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(1,12.83452);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(2,42.53769);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(3,76.25879);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(4,59.45185);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(5,29.95708);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(6,9.072501);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(7,46.42922);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetBinError(8,24.28802);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetEntries(1284);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.168915e-316,2.352069e-310,8.16947e-316,8.814737e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
