{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:51 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(1,95);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(2,904);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(3,3174);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(4,1713);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(5,579);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(6,23);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(7,1206);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(8,256);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(1,328.9343);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(2,3043.113);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(3,10801.86);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(4,5814.276);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(5,1984.464);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(6,84.25737);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(7,4091.513);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(8,853.8032);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(1,34.51969);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(2,102.8496);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(3,194.7721);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(4,142.8306);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(5,83.94851);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(6,17.88816);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(7,119.6897);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(8,54.26638);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetEntries(7950);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.913547e-316,2.352069e-310,6.436445e-316,6.436407e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
