{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:08 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",8,0,8,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,27);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,10);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,3);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(7,12);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,36.49543);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,103.0343);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,38.93479);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,10.3727);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(7,47.66679);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,3.823868);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,11.69181);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,20.31024);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,12.66569);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,5.999656);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(7,14.00362);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,3.823868);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(63);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.551019e-316,7.291122e-304,2.352068e-310,6.556765e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
