{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:51:32 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMetDeDxFiltermyHist","",8,0,8,"");
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(1,13);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(2,156);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(3,464);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(4,308);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(5,67);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(6,6);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(7,165);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(8,51);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(1,53.34374);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(2,617.6576);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(3,1835.887);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(4,1216.022);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(5,266.9355);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(6,23.725);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(7,657.4945);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(8,201.0161);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(1,15.08469);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(2,50.29358);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(3,86.36429);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(4,70.43638);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(5,33.08894);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(6,9.87859);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(7,52.04521);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(8,28.46938);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetEntries(1230);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.948028e-316,2.352069e-310,2.352068e-310,8.946342e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
