{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:50:43 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(1,2871);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(2,26387);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(3,88446);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(4,50056);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(5,15786);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(6,529);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(7,36012);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(8,8001);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(1,8281.254);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(2,75191.07);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(3,253759.8);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(4,142816.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(5,45149.89);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(6,1514.514);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(7,103081.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(8,22774.48);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(1,156.541);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(2,468.868);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(3,864.1044);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(4,646.77);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(5,364.0013);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(6,66.69749);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(7,549.9986);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(8,258.2264);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetEntries(228088);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.168904e-316,2.352069e-310,2.352068e-310,8.949579e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("c");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
