{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:03 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",8,0,8,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,37);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,14);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,18);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,29.38444);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,125.8747);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,46.35486);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,16.53097);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,58.86056);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,3.12909);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,9.817186);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,20.71665);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,12.43359);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,7.407081);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,13.8902);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,3.12909);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(84);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.913604e-316,2.352069e-310,8.168696e-316,6.390855e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
