{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:51:30 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,14);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,139);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,451);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,280);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,68);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,7);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(7,161);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(8,48);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,48.43986);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,469.6697);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,1493.549);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,935.2398);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,224.1006);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,22.89674);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(7,535.9818);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(8,162.2259);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,13.27907);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,40.50107);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,71.39032);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,56.76082);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,27.74411);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,8.846631);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(7,43.07245);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(8,23.66985);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(1168);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.948028e-316,2.352069e-310,6.458795e-316,6.913621e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
