{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:53:06 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",8,0,8,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,32);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(5,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,13);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(8,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,19.01895);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,99.1437);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,23.21635);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(5,11.29613);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,41.82478);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(8,3.459965);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,7.890596);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,17.99388);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,8.326157);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(5,5.696628);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,11.83038);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(8,3.459965);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(64);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206605");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206744");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206745");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206859");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206866");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206868");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206869");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206897");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.390802e-316,7.291122e-304,2.352068e-310,9.489565e-311,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
