{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 13:52:55 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",4,0,4,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,17045);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,15727);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,103012);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,92738);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,56254.86);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,51916.04);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,342080.8);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,307328.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,431.6715);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,414.7319);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,1067.821);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,1011.079);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(228522);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"198941");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"198954");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"198955");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"198969");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.259752e-316,6.921047e-316,2.361728e-310,7.563755e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
