{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Aug 21 18:22:52 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMPProf","",14,0,14,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(2,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(3,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(4,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(6,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(7,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(9,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(10,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(12,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinEntries(14,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(2,7.09377);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(3,9.483395);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(4,23.66854);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(6,3.082765);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(7,21.39326);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(9,7.4214);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(10,6.971079);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(12,23.25791);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinContent(14,3.180093);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(2,5.020117);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(3,5.481007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(4,8.975118);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(6,3.082765);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(7,9.856132);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(9,5.25014);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(10,4.930938);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(12,8.815657);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetBinError(14,3.180093);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetEntries(30);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"206066");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"206088");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"206102");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"206187");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"206188");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"206199");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"206207");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"206208");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"206210");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(10,"206243");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(11,"206245");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(12,"206246");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(13,"206257");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(14,"206258");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.172411e-316,2.332864e-310,8.172417e-316,5.97465e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
