{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:17:13 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFiltermyHist = new TProfile("HSCPHLTTriggerHtDeDxFiltermyHist","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(1,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(2,9);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(3,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(4,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(5,15);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(6,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(10,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(11,8);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinEntries(12,6);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(1,6.339801);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(2,32.25762);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(3,29.60246);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(4,7.597631);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(5,55.35937);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(6,22.2254);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(8,7.699222);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(10,23.2664);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(11,29.30713);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinContent(12,24.42348);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(1,4.484595);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(2,10.83865);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(3,10.53474);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(4,5.450714);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(5,14.4327);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(6,9.172193);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(8,5.454099);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(10,9.571665);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(11,10.43571);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetBinError(12,10.19195);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetEntries(64);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"208390");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"208391");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"208427");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"208428");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"208429");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"208487");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"208509");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"208538");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"208540");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(10,"208541");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(11,"208551");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBinLabel(12,"208686");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.10874e-316,2.371611e-310,7.840385e-316,6.770017e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
