{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 22 14:17:10 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",12,0,12,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(1,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(3,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,16);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,2);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(10,6);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(11,12);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(12,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(1,6.703913);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,35.21227);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(3,40.3236);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,16.80562);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,53.06462);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,19.5258);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,6.501744);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(10,19.80173);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(11,40.40771);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(12,23.21332);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(1,4.740999);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,10.62912);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(3,11.674);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,7.519121);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,13.28606);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,7.976754);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,4.602494);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(10,8.105684);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(11,11.6889);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(12,8.787414);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(79);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"208390");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"208391");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"208427");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"208428");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"208429");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"208487");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"208509");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"208538");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"208540");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(10,"208541");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(11,"208551");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(12,"208686");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(7.473566e-316,7.291122e-304,2.371609e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
