{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:25:49 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFiltermyHist = new TProfile("HSCPHLTTriggerMetDeDxFiltermyHist","",9,0,9,"");
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(1,256);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(2,24);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(3,2);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(4,168);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(5,138);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(6,107);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(7,64);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(8,67);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinEntries(9,256);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(1,1011.67);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(2,93.15758);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(3,6.988924);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(4,660.8942);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(5,557.3049);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(6,424.0074);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(7,250.6777);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(8,285.8146);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinContent(9,1036.513);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(1,64.3303);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(2,19.21015);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(3,4.968253);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(4,51.68644);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(5,48.18046);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(6,41.92261);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(7,31.70748);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(8,35.92385);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetBinError(9,65.83091);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetEntries(1082);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetStats(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.637367e-316,7.291122e-304,2.368194e-310,8.755305e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
