{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:26:47 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMProf","",9,0,9,"");
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(1,1594);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(2,193);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(3,16);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(4,967);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(5,961);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(6,745);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(7,438);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(8,416);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinEntries(9,1623);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(1,5001.074);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(2,603.8879);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(3,52.16149);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(4,3041.449);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(5,2959.396);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(6,2291.505);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(7,1344.528);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(8,1273.971);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinContent(9,5014.429);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(1,125.6726);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(2,43.56063);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(3,13.05461);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(4,98.09684);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(5,95.79589);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(6,84.22017);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(7,64.49356);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(8,62.66151);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetBinError(9,124.9178);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetEntries(6953);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(4.574949e-316,2.368196e-310,2.368194e-310,8.73264e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
