{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:24:52 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFiltermyHist = new TProfile("HSCPHLTTriggerMuFiltermyHist","",9,0,9,"");
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(1,45461);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(2,5762);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(3,531);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(4,31893);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(5,28887);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(6,20396);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(7,13600);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(8,11124);
   HSCPHLTTriggerMuFiltermyHist->SetBinEntries(9,54374);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(1,158721.1);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(2,20088.05);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(3,1867.417);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(4,111593);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(5,101262.6);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(6,71409.78);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(7,47680.72);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(8,38955.81);
   HSCPHLTTriggerMuFiltermyHist->SetBinContent(9,191097);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(1,750.7686);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(2,266.8694);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(3,81.79141);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(4,630.1133);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(5,601.164);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(6,504.6981);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(7,412.4421);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(8,372.6928);
   HSCPHLTTriggerMuFiltermyHist->SetBinError(9,826.6692);
   HSCPHLTTriggerMuFiltermyHist->SetEntries(212028);
   HSCPHLTTriggerMuFiltermyHist->SetStats(0);
   HSCPHLTTriggerMuFiltermyHist->SetFillColor(1);
   HSCPHLTTriggerMuFiltermyHist->SetLineStyle(0);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerStyle(20);
   HSCPHLTTriggerMuFiltermyHist->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFiltermyHist->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFiltermyHist->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFiltermyHist->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFiltermyHist->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.729755e-316,2.368196e-310,8.729142e-316,9.401347e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
