{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:29:20 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMSProf","",9,0,9,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(1,1530);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(2,176);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(3,15);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(4,1092);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(5,861);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(6,551);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(7,435);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(8,318);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinEntries(9,1755);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(1,5216.317);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(2,599.5495);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(3,51.97234);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(4,3747.407);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(5,2939.81);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(6,1874.205);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(7,1491.304);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(8,1081.064);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinContent(9,6010.322);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(1,133.6898);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(2,45.2932);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(3,13.45931);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(4,113.6834);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(5,100.4264);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(6,80.03915);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(7,71.6942);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(8,60.79873);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetBinError(9,143.8129);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetEntries(6733);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.754443e-316,2.368196e-310,2.368194e-310,6.916173e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
