{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:25:42 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMProf","",9,0,9,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(1,239);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(2,20);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(3,1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(4,180);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(5,137);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(6,97);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(7,69);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(8,63);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinEntries(9,260);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(1,803.2747);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(2,68.03079);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(3,3.062082);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(4,601.4651);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(5,446.5699);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(6,323.2665);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(7,228.9613);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(8,211.1216);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinContent(9,856.5044);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(1,52.11951);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(2,15.24152);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(3,3.062082);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(4,45.01464);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(5,38.32663);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(6,32.88328);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(7,27.65582);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(8,26.67915);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetBinError(9,53.27887);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetEntries(1066);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.401314e-316,2.368196e-310,2.368194e-310,4.571927e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
