{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:25:47 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMetDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMetDeDxFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(1,238);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(2,21);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(3,1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(4,167);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(5,123);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(6,94);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(7,64);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(8,61);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinEntries(9,238);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(1,848.0774);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(2,73.46538);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(3,2.868268);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(4,580.4388);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(5,418.9004);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(6,316.7882);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(7,209.1227);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(8,225.758);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinContent(9,811.4673);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(1,56.15795);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(2,16.22197);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(3,2.868268);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(4,45.70967);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(5,38.47969);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(6,33.45329);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(7,26.56738);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(8,29.8601);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetBinError(9,53.53532);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetEntries(1007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMetDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.879943e-316,7.291122e-304,2.368194e-310,0,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("h");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
