{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:29:22 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(1,1521);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(2,181);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(3,15);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(4,1085);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(5,836);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(6,539);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(7,432);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(8,310);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinEntries(9,1721);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(1,5369.458);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(2,640.4787);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(3,52.06291);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(4,3864.37);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(5,2815.066);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(6,1839.955);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(7,1444.309);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(8,1058.802);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinContent(9,5819.377);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(1,140.0072);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(2,48.3358);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(3,13.5351);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(4,119.1293);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(5,98.97723);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(6,80.54785);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(7,70.54406);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(8,61.20755);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetBinError(9,142.4902);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetEntries(6640);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.6368e-316,2.368196e-310,9.636815e-316,9.636801e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("g");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
