{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:27:49 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMProf","",9,0,9,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(1,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(4,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(5,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(6,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(7,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(8,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinEntries(9,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(1,22.76781);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(2,3.447557);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(4,28.83301);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(5,25.47523);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(6,12.24986);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(7,9.803477);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(8,16.65246);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinContent(9,34.07189);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(1,8.652765);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(2,3.447557);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(4,9.628637);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(5,9.030126);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(6,6.141045);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(7,5.664282);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(8,7.459857);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetBinError(9,10.2987);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetEntries(48);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.733166e-316,7.291122e-304,2.368194e-310,1.710185e+214,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
