{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:28:02 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerHtDeDxFilterdEdxMSProf = new TProfile("HSCPHLTTriggerHtDeDxFilterdEdxMSProf","",9,0,9,"");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(1,7);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(2,1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(4,9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(5,8);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(6,4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(7,3);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(8,5);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinEntries(9,11);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(1,24.12165);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(2,3.475834);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(4,30.61432);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(5,26.47867);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(6,13.31165);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(7,10.98518);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(8,16.48665);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinContent(9,36.19144);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(1,9.160072);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(2,3.475834);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(4,10.21928);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(5,9.377302);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(6,6.660229);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(7,6.349111);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(8,7.380272);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetBinError(9,10.93881);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetEntries(48);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerHtDeDxFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(8.708763e-316,2.368196e-310,8.633118e-316,6.413078e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("f");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
