{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:26:52 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerL2MuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerL2MuFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(1,1300);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(2,152);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(3,15);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(4,781);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(5,658);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(6,520);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(7,293);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(8,274);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinEntries(9,1168);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(1,3931.279);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(2,455.0969);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(3,44.57497);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(4,2344.765);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(5,1893.396);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(6,1482.537);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(7,833.5258);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(8,797.716);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinContent(9,3375.305);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(1,110.4244);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(2,37.30484);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(3,11.62519);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(4,85.01987);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(5,74.74443);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(6,65.81196);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(7,49.23082);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(8,49.15634);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetBinError(9,100.0903);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetEntries(5161);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerL2MuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(6.764404e-316,7.291122e-304,2.368194e-310,9.485321e-311,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("e");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
