{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:29:09 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuDeDxFilterdEdxMProf = new TProfile("HSCPHLTTriggerMuDeDxFilterdEdxMProf","",9,0,9,"");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(1,1530);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(2,176);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(3,15);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(4,1092);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(5,861);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(6,551);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(7,435);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(8,318);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinEntries(9,1755);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(1,5176.072);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(2,595.6754);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(3,51.59585);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(4,3720.521);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(5,2881.308);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(6,1843.146);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(7,1458.129);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(8,1058.427);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinContent(9,5905.448);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(1,132.6846);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(2,44.99689);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(3,13.34652);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(4,112.9087);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(5,98.46369);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(6,78.7089);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(7,70.12704);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(8,59.55338);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetBinError(9,141.3036);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetEntries(6733);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetStats(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetFillColor(1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetLineStyle(0);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuDeDxFilterdEdxMProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.6368e-316,2.368196e-310,2.368194e-310,8.771494e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
