{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:24:48 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMSProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMSProf","",9,0,9,"");
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(1,60088);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(2,7679);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(3,685);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(4,43207);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(5,37242);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(6,25879);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(7,17850);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(8,13996);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinEntries(9,70596);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(1,197245.8);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(2,25217.94);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(3,2250.735);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(4,142327.7);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(5,122182);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(6,84805.49);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(7,58693.56);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(8,45863.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinContent(9,232344.7);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(1,806.1197);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(2,288.2919);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(3,86.1578);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(4,685.971);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(5,634.2604);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(6,528.0985);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(7,440.0957);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(8,388.377);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetBinError(9,876.0395);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetEntries(277222);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMSProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMSProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMSProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(4.575117e-316,2.368196e-310,7.533699e-316,9.636928e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("b");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
