{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 26 11:24:50 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.07);
   c1->SetRightMargin(0.03);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TProfile *HSCPHLTTriggerMuFilterdEdxMPProf = new TProfile("HSCPHLTTriggerMuFilterdEdxMPProf","",9,0,9,"");
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(1,47467);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(2,6109);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(3,555);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(4,35378);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(5,25722);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(6,17401);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(7,12596);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(8,9432);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinEntries(9,50577);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(1,142066.5);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(2,18238.14);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(3,1667.446);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(4,105975.7);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(5,73550.52);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(6,49711.91);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(7,36013.48);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(8,26977.78);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinContent(9,144938.3);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(1,660.8098);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(2,236.4755);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(3,71.72434);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(4,570.7274);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(5,464.681);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(6,382.1109);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(7,325.1373);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(8,281.5704);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetBinError(9,652.7263);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetEntries(205237);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetStats(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetFillColor(1);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetLineStyle(0);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerStyle(20);
   HSCPHLTTriggerMuFilterdEdxMPProf->SetMarkerSize(0.4);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(1,"205718");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(2,"205774");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(3,"205777");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(4,"205781");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(5,"205826");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(6,"205833");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(7,"205834");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(8,"205908");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBinLabel(9,"205921");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetBit(TAxis::kLabelsVert);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetNdivisions(505);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleOffset(1.1);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetXaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitle("dE/dx estimator");
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleOffset(0.9);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetYaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelOffset(0.007);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetLabelSize(0.05);
   HSCPHLTTriggerMuFilterdEdxMPProf->GetZaxis()->SetTitleFont(42);
   HSCPHLTTriggerMuFilterdEdxMPProf->Draw("E1");
   
   TPaveText *pt = new TPaveText(9.636913e-316,2.368196e-310,4.575119e-316,6.731736e-316,"brNDC");
   pt->SetFillColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(43);
   pt->SetTextSize(21);
   TText *text = pt->AddText("c");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
